"use client";

import './globals.css'
import styles from './page.module.css'
import { Inter } from 'next/font/google'

import Head from 'next/head'

import Header from './components/general/header/Header'
import Banner from './components/general/banner/Banner'
import Footer from './components/general/footer/Footer'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CityDom',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {

  let [path, setPath] = useState('/')
  let [device, setDevice] = useState('desktop')

  useEffect(() => {
    if(window.innerWidth < 768) {
      setDevice('mobile')
    }
    setPath(window.location.pathname)
    window.addEventListener('resize', () => {
      if(window.innerWidth < 768) {
        setDevice('mobile')
      }
      else {
        setDevice('desktop')
      }
    })

    window.addEventListener('popstate', () => {
      setPath(window.location.pathname)
    })
  }, [])

  return (
    <html lang="en">
      
        {
          <Head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link href="https://fonts.googleapis.com/css2?family=Noto+Color+Emoji&display=swap" rel="stylesheet" />
          </Head>
        }
      <body className={inter.className}>
        <div className={styles.wrapper}>
          {
            (device !== 'mobile' || path === '/' || path === '/citydom/') && <Header />
          }
          
          <Banner />
          {children}
          {
            (device !== 'mobile' || path === '/' || path === '/citydom/') && <Footer />
          }
          
        </div>        
      </body>
    </html>
  )
}
